/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function setupFromCircomR1CsBn128(
  r1CsFilePath: string,
  commitWitnessCount: number,
  seed: number,
  pathPk: string,
  pathVk: string,
): void
export function setupFromCircomR1CsBls12381(
  r1CsFilePath: string,
  commitWitnessCount: number,
  seed: number,
  pathPk: string,
  pathVk: string,
): void
export function proveRangeBn128(
  r1CsFilePath: string,
  wasmFilePath: string,
  pkFilePath: string,
  proofFilePath: string,
  inputString: string,
  seed: number,
): void
export function proveRangeBls12381(
  r1CsFilePath: string,
  wasmFilePath: string,
  pkFilePath: string,
  proofFilePath: string,
  inputString: string,
  seed: number,
): void
export function verifyRangeBn128(vkPath: string, proofFilePath: string): void
export function getProofBn128(proofFilePath: string): string
export function aggregateProofCommitmentBn128(proofFilePaths: Array<string>, saveFilePath: string): void
export function aggregateProofCommitmentBls12381(proofFilePaths: Array<string>, saveFilePath: string): void
export function aggregateOpeningKeysBn128(openingKeyFilePaths: Array<string>, saveFilePath: string): void
export function aggregateOpeningKeysBls12381(openingKeyFilePaths: Array<string>, saveFilePath: string): void
export function calculatePedersenCommitmentBn128(provingFilePath: string, m: string, v: string): string
