/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export function setupFromCircomR1CsBn128(
  r1CsFilePath: string,
  commitWitnessCount: number,
  seed: number,
  path: string,
): void
export function setupFromCircomR1CsBls12381(
  r1CsFilePath: string,
  commitWitnessCount: number,
  seed: number,
  path: string,
): void
export function proveRangeBn128(
  r1CsFilePath: string,
  keyFilePath: string,
  wasmFilePath: string,
  inputString: string,
  seed: number,
): void
